esphome:
  name: raspiaudio-radio
  friendly_name: RaspiAudio Radio
  name_add_mac_suffix: true
  project:
    name: raspiaudio.radio
    version: "1.0"
  min_version: 2023.5.0
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
                     
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 4MB
  framework:
    type: arduino
#  variant: esp32s3  
  
logger:

api:

ota:

i2c:
  sda: GPIO18
  scl: GPIO11

dashboard_import:
  package_import_url: github://RASPIAUDIO/esphomeRadio/radio.yaml@main

wifi:
  ap:

captive_portal:

improv_serial:

external_components:
  - source: github://RASPIAUDIO/esphomeRadio@main
    components: [es8388]
    refresh: 0s

es8388:

i2s_audio:
  - i2s_lrclk_pin: GPIO16
    i2s_bclk_pin: GPIO5
      
media_player:
  - platform: i2s_audio
    name: none
    id: radio_out
    dac_type: external
    i2s_dout_pin: GPIO17
    mode: stereo
    mute_pin:
        number: GPIO46
        inverted: true
        ignore_strapping_warning: true



