esphome:
  name: raspiaudioradio
  friendly_name: RaspiAudio Radio
  name_add_mac_suffix: false
  
  project:
    name: raspiaudio.radio
    version: "1.0"
  min_version: 2023.5.0
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
#        - media_player.play_media: http://direct.fipradio.fr/live/fip-lofi.mp3    
        - sensor.rotary_encoder.set_value:
            id: volencoder  
            value: 50
        - media_player.volume_set: 50%
        - output.turn_on: dac_mute

                          
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 4MB
  framework:
    type: arduino
  variant: esp32s3  
  
logger:

api:

ota:

improv_serial:

output:
   - platform: gpio
     id:  dac_mute
     pin: GPIO046
     inverted: false

i2c:
  sda: GPIO18
  scl: GPIO11

wifi:
  ap:

captive_portal:

external_components:
  - source: github://RASPIAUDIO/esphomeRadio@main
    components: [ es8388 ]
    refresh: 0s
    
es8388:
    
i2s_audio:
  - i2s_lrclk_pin: GPIO16
    i2s_bclk_pin: GPIO05
    i2s_mclk_pin: GPIO00

    
      
media_player:
  - platform: i2s_audio
    name: radio_media_player
    id: radio_out
    dac_type: external
    i2s_dout_pin: GPIO17
    mode: stereo


sensor:
  - platform: rotary_encoder
    id: volencoder
    name: volume
    pin_a: 
      number: 42
      inverted: false
      mode:
        input: true
        pullup: true
    pin_b: 
      number: 3
      inverted: false
      mode:
        input: true
        pullup: true    
    min_value: 0
    max_value: 100
    publish_initial_value: true
    on_value:
      - then:
          media_player.volume_set: !lambda "return x/100;"
          
  - platform: rotary_encoder
    id: staencoder
    name: stations
    pin_a: 
      number: 6
      inverted: false
      mode:
        input: true
        pullup: true
    pin_b: 
      number: 7
      inverted: false
      mode:
        input: true
        pullup: true    
    min_value: 0
    max_value: 100
    publish_initial_value: true
    on_value:
      - then:    
      
      
binary_sensor:
  - platform: gpio
    name: pause
    pin:
      number: 48
      inverted: true
      mode:
        input: true
        pullup: true 
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: 
          
  - platform: gpio
    name: assist
    pin:
      number: 45
      inverted: true
      mode:
        input: true
        pullup: true 
    on_multi_click:
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start: 
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms          
        then:
          - voice_assistant.stop:
                
microphone:
  - platform: i2s_audio
    id: radio_microphone
    i2s_din_pin: GPIO04
    adc_type: external
    pdm: false
   
voice_assistant:
   id: va
   microphone: radio_microphone
   media_player: radio_out
   use_wake_word: false

               
          

              
      

